const HERO_URL="https://raw.githubusercontent.com/p3hndrx/MLBB-API/main/v1/hero-meta-final.json";
const ITEM_URL="https://raw.githubusercontent.com/p3hndrx/MLBB-API/main/item-meta.json";
const EMBLEM_URL="https://raw.githubusercontent.com/p3hndrx/MLBB-API/main/emblem-meta.json";

let heroes=[],items=[],emblems=[],page="heroes";
const customBuilds={Marksman:["Demon Hunter Sword","Golden Staff","Corrosion Scythe","Windtalker","Malefic Roar","Rose Gold Meteor"],Mage:["Arcane Boots","Clock of Destiny","Lightning Truncheon","Holy Crystal","Divine Glaive","Blood Wings"],Assassin:["Rapid Boots","Blade of the Heptaseas","Hunter Strike","Blade of Despair","Malefic Roar","Immortality"],Fighter:["Warrior Boots","War Axe","Brute Force Breastplate","Hunter Strike","Queen's Wings","Immortality"],Tank:["Tough Boots","Dominance Ice","Athena's Shield","Antique Cuirass","Immortality","Guardian Helmet"],Support:["Demon Shoes","Enchanted Talisman","Fleeting Time","Oracle","Immortality","Dominance Ice"]};
const customEmblems={Marksman:"Marksman Emblem - Weapon Master + Quantum Charge",Mage:"Mage Emblem - Bargain Hunter + Lethal Ignition",Assassin:"Assassin Emblem - Master Assassin + Killing Spree",Fighter:"Fighter Emblem - Festival of Blood + Brave Smite",Tank:"Tank Emblem - Tenacity + Concussive Blast",Support:"Support Emblem - Pull Yourself Together + Focusing Mark"};
const tierByRole={Assassin:"S",Marksman:"A",Mage:"A",Fighter:"A",Tank:"B",Support:"B"};

const content=document.getElementById("content"),title=document.getElementById("pageTitle"),search=document.getElementById("searchInput"),roleFilter=document.getElementById("roleFilter");

document.querySelectorAll(".tab").forEach(btn=>btn.onclick=()=>{document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");page=btn.dataset.page;render();});
search.oninput=render;roleFilter.onchange=render;

async function getJson(url){const r=await fetch(url); if(!r.ok) throw new Error(url); return await r.json();}
async function load(){showNotice("Loading MLBB API data..."); try{const heroJson=await getJson(HERO_URL); heroes=(heroJson.data||[]).filter(h=>h.hero_name&&h.hero_name!=="None");}catch(e){heroes=fallbackHeroes();}
try{const itemJson=await getJson(ITEM_URL); items=itemJson.data||[];}catch(e){items=[];}
try{const emblemJson=await getJson(EMBLEM_URL); emblems=emblemJson.data||[];}catch(e){emblems=[];}
render();}
function filteredHeroes(){const q=search.value.toLowerCase().trim(), r=roleFilter.value;return heroes.filter(h=>{const text=[h.hero_name,h.class,(h.laning||[]).join(" ")].join(" ").toLowerCase();const okQ=!q||text.includes(q);const okR=r==="all"||String(h.class||"").toLowerCase().includes(r);return okQ&&okR;});}
function setTitle(h,p){title.innerHTML=`<h2>${h}</h2><p>${p}</p>`;}
function render(){if(page==="heroes")return renderHeroes();if(page==="builds")return renderBuilds();if(page==="emblems")return renderEmblems();if(page==="counters")return renderCounters();if(page==="calculator")return renderCalculator();if(page==="tiers")return renderTiers();}
function heroCard(h,extra=""){return `<article class="card"><img class="hero-img" src="${h.portrait||''}" onerror="this.style.display='none'"><h3>${h.hero_name}</h3><p class="muted">${h.class||"Unknown"} • ${(h.laning||[]).join(", ")||"No lane"}</p><div class="chip-row">${(h.speciality||[]).map(x=>`<span class="chip">${x}</span>`).join("")}</div>${extra}<div class="card-actions"><button onclick="openGuide('${h.id}')">Guide</button><button class="ghost" onclick="openRaw('${h.id}')">Raw</button></div></article>`;}
function renderHeroes(){setTitle("✅ Hero Guides","Shows hero role, lane, speciality, skills, counters, and synergies from hero-meta-final.json.");content.className="content-grid";content.innerHTML=filteredHeroes().map(h=>heroCard(h)).join("")||empty();}
function renderBuilds(){setTitle("✅ Best Build","Auto build recommendation by hero class. You can edit customBuilds inside app.js.");content.className="content-grid";content.innerHTML=filteredHeroes().map(h=>{const role=mainRole(h),build=customBuilds[role]||customBuilds.Fighter;return heroCard(h,`<div class="info-box"><b>Best Build</b><br>${build.map(i=>`• ${i}`).join("<br>")}</div>`);}).join("")||empty();}
function renderEmblems(){setTitle("✅ Best Emblem","Auto emblem recommendation by hero class. You can edit customEmblems inside app.js.");content.className="content-grid";content.innerHTML=filteredHeroes().map(h=>{const role=mainRole(h);return heroCard(h,`<div class="info-box"><b>Best Emblem</b><br>${customEmblems[role]||customEmblems.Fighter}</div>`);}).join("")||empty();}
function renderCounters(){setTitle("✅ Counter Heroes","Uses the built-in counters and synergies arrays from hero-meta-final.json.");content.className="content-grid";content.innerHTML=filteredHeroes().map(h=>heroCard(h,`<div class="info-box"><b>Counters:</b><br>${names(h.counters)}</div><div class="info-box"><b>Synergy:</b><br>${names(h.synergies)}</div>`)).join("")||empty();}
function renderCalculator(){setTitle("✅ Hero Stats Calculator","Simple calculator concept: Hero Base + Emblem + Item. Since this API mostly has guide metadata, this demo adds custom bonuses.");content.className="content-grid";content.innerHTML=`<div class="card"><h3>Calculator</h3><div class="calc-row"><select id="calcHero">${heroes.map(h=>`<option value="${h.id}">${h.hero_name}</option>`).join("")}</select><input id="bonus" type="number" value="100" placeholder="Bonus points"></div><button onclick="calcStats()">Calculate</button><div id="calcResult" class="info-box">Select hero and calculate.</div></div><div class="card"><h3>Formula</h3><p class="muted">Hero Base Attributes + Emblem Modifiers + Equipment/Item Modifiers.</p><p class="muted">You can connect real item/emblem modifiers once available in the JSON.</p></div>`;}
function renderTiers(){setTitle("✅ Tier List System","Auto tier by role. You can edit tierByRole inside app.js to match your own meta.");content.className="content-grid";content.innerHTML=filteredHeroes().map(h=>{const role=mainRole(h),tier=tierByRole[role]||"B";return heroCard(h,`<div class="tier">${tier}</div><p class="muted">${role} Tier</p>`);}).join("")||empty();}
function openGuide(id){const h=heroes.find(x=>x.id===id);if(!h)return;document.getElementById("modalContent").innerHTML=`<h2>${h.hero_name}</h2><p class="muted">${h.class} • ${(h.laning||[]).join(", ")}</p><div class="two-col"><div class="info-box"><b>Best Build</b><br>${(customBuilds[mainRole(h)]||[]).map(i=>`• ${i}`).join("<br>")}</div><div class="info-box"><b>Best Emblem</b><br>${customEmblems[mainRole(h)]||"Custom"}</div></div><div class="two-col"><div class="info-box"><b>Counters</b><br>${names(h.counters)}</div><div class="info-box"><b>Synergies</b><br>${names(h.synergies)}</div></div><h3>Skills</h3><div class="skills">${(h.skills||[]).map(s=>`<div class="skill"><img src="${skillIcon(h,s)}" onerror="this.style.display='none'"><b>${s.skill_name}</b><p class="muted">${s.type} • CD: ${s.cooldown} • Mana: ${s.manacost}</p><p>${clean(s.description).slice(0,350)}...</p></div>`).join("")}</div>`;openModal();}
function openRaw(id){const h=heroes.find(x=>x.id===id);document.getElementById("modalContent").innerHTML=`<h2>${h.hero_name} Raw JSON</h2><pre>${escapeHtml(JSON.stringify(h,null,2))}</pre>`;openModal();}
function calcStats(){const h=heroes.find(x=>x.id===document.getElementById("calcHero").value);const b=Number(document.getElementById("bonus").value||0);document.getElementById("calcResult").innerHTML=`<b>${h.hero_name}</b><br>Role: ${h.class}<br>Lane: ${(h.laning||[]).join(", ")}<br>Custom Bonus: +${b}<br>Estimated Power Score: ${1000+b+(h.skills||[]).length*100}`;}
function mainRole(h){const c=String(h.class||"Fighter");return ["Tank","Fighter","Assassin","Mage","Marksman","Support"].find(r=>c.includes(r))||"Fighter";}
function names(arr){return (arr&&arr.length)?arr.map(x=>`• ${x.heroname||x.name}`).join("<br>"):"No data";}
function skillIcon(h,s){return s.skill_icon&&s.skill_icon.startsWith("http")?s.skill_icon:`https://raw.githubusercontent.com/p3hndrx/MLBB-API/main/v1/${s.skill_icon||""}`;}
function clean(t){return String(t||"").replace(/\n+/g," ").replace(/\s+/g," ").trim();}
function showNotice(t){content.className="content-grid";content.innerHTML=`<div class="notice">${t}</div>`;}
function empty(){return `<div class="notice">No result found.</div>`;}
function openModal(){document.getElementById("modal").style.display="block"}function closeModal(){document.getElementById("modal").style.display="none"}
function escapeHtml(s){return s.replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[m]));}
function fallbackHeroes(){return [{hero_name:"Miya",id:"h001",class:"Marksman",laning:["gold lane"],speciality:["Finisher","Damage"],skills:[],counters:[{heroname:"Belerick"}],synergies:[{heroname:"Tigreal"}]},{hero_name:"Saber",id:"h003",class:"Assassin",laning:["jungle"],speciality:["Charge","Finisher"],skills:[],counters:[{heroname:"Barats"}],synergies:[{heroname:"Lolita"}]}];}
load();
